language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: DEPS=lowest
    - php: 5.6
      env: DEPS=latest
    - php: 7.0
      env: DEPS=lowest
    - php: 7.0
      env: DEPS=latest
    - php: 7.1
      env: DEPS=lowest
    - php: 7.1
      env: DEPS=latest
    - php: 7.2
      env: DEPS=lowest
    - php: 7.2
      env: DEPS=latest
    - php: 7.3
      env: DEPS=lowest
    - php: 7.3
      env: DEPS=latest

install:
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update --no-interaction ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --no-interaction --prefer-lowest ; fi

script: phpunit --configuration tests/
